<?php

namespace AppBundle\Repository;

/**
 * FuelTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuelTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
