# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:
    #parameter_name: value

services:
    app.web_crawler:
        class: AppBundle\Service\WebCrawler
        arguments: ['@event_dispatcher', '@doctrine.orm.entity_manager']